[package]
name = "weedesktop_macro"
version = "0.1.0"
authors = ["Andreas Runfalk <andreas@runfalk.se>"]

[lib]
proc-macro = true

[dependencies]
quote = "^0.6.8"
syn = { version = "^0.15.13", features = ["full"] }

[build-dependencies]
bindgen = "^0.43.0"
